
quit = "^+ q"
restart = "^+ w"
debug = "^+ d"

[connection]
start = ["enter", "numpadenter"]

[server]
disconnect = "^+ delete"

[server.lobby]
disconnect = "escape"
focus_create = "^ n"
focus_list = "^ j"

[server.game]
leave = "escape"
