
quit = "^+ q"
restart = "^+ w"
debug = "^+ d"
show_client = "^+ home"
show_server = "^+ end"

[client]
leave_game = "^ home"

[client.connect]
start = ["enter", "numpadenter"]

[client.lobby]
focus_create = "^ n"
focus_list = "^ j"
show_admin_panel = "^ end"
