
quit = "^+ q"
restart = "^+ w"
debug = "^+ d"
disconnect = "^+ home"

[connection]
start = ["enter", "numpadenter"]

[server]
leave_game = "^ home"

[server.lobby]
focus_create = "^ n"
focus_list = "^ j"
show_admin_panel = "^ end"
