
quit = "^+ q"
restart = "^+ w"
debug = "^+ d"
show_client = "^+ f1"
show_server = "^+ f2"

[server]
focus = "^ `"
shutdown = "^ q"

[client.connect]
focus = "^ `"

[client.user]
disconnect = "^+ home"
leave_game = "^ home"
show_lobby = "f1"
show_game = "f2"
show_admin = "f3"

[client.user.lobby]
focus = "^ `"
focus_create = "^ n"
focus_list = "^ j"

[client.user.admin]
focus = "^ `"
